### ISSUE TITLE
Fork'able?

### ISSUE THREAD

**Issue by wdiechmann** [surface-ui/surface_tailwind#2]
I'd like to fork this repo - with the intention to PR some componentization ideas addressing TailwindCSS

**Comment by msaraiva** [comment]
Hi @wdiechmann!

I think you should be able to submit a PR now.

**Comment by wdiechmann** [comment]
Thx a lot Marius - but look what the Tailwind guys wrote:

Thanks for reaching out. Unfortunately, packaging different Tailwind UI components like this, is somewhat creating a "re-distribution channel" for Tailwind UI.

We don't have any sort of API for licence verification, and quite honestly don't really want to at this point, so we can keep things simple in terms of how Tailwind UI is being distributed.

There is absolutely no problem in you creating your own little system to build apps with Tailwind UI within your licence rights, but this is likely not something you should be making public for other users to use.

Sorry about the potentially disappointing response, and thank you for your understanding!
– Simon


Med venlig hilsen
Walther
